spring:
  rabbitmq:
    addresses: amqps://eaeuwium:qsiuCrHd0S_PDB9wCBScAOh3ZMZTNSBf@stingray.rmq.cloudamqp.com/eaeuwium
  mail:
    host: smtp.gmail.com
    port: 587
    username: jouzera.teste@gmail.com
    password: Teste360.
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
queue:
  drone: drone.report.status
server:
  port: 8081

